# -*- encoding: utf-8 -*-

{
    'name': 'Merchant Account Management',
    'version': '17.0.0.1',
    'category': 'Website/Website',
    'summary': 'Payment Acquirer: BlueMaxPay Implementation',
    'depends': ['base_setup', 'portal', 'auth_signup', 'website'],
    'data': [
        'security/ir.model.access.csv',
        'data/page_data.xml',
        'data/propay.error.codes.csv',
        'data/device_data.xml',
        'data/account_type_data.xml',
        'data/propaytitle_page_data.xml',
        'report/agreement_report.xml',
        'views/res_users.xml',
        'views/auth_signup_login.xml',
        'views/portal_templates.xml',
        'views/merchant_signup_template.xml',
        'views/bluemaxpay_logs_views.xml',
        'views/bread_crumbs_loaded.xml',
        'views/mcc_code.xml',
        'views/res_partner.xml',
        'views/res_config_settings_views.xml',
        'wizard/create_merchant.xml',
        'wizard/merchant_address.xml',
        'wizard/order_device.xml',
        'wizard/renew_account.xml',
        'wizard/single_sign_on.xml',
        'wizard/ach_transaction.xml',
        'wizard/document_upload.xml',
    ],
    'assets': {
        'web.assets_frontend': [
            'bluemaxpay_account_management/static/src/js/signup.js',
            'bluemaxpay_account_management/static/src/js/portal.js',
            'bluemaxpay_account_management/static/src/scss/signup_page.scss',
            'bluemaxpay_account_management/static/src/scss/portal.scss',
        ],
        'web.assets_backend': [
            'bluemaxpay_account_management/static/src/js/single_sign_on.js',
            'bluemaxpay_account_management/static/src/xml/single_sign_on.xml'
        ],
    },
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
    'module_type': 'official',
}
